// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpajriwrusrvkrkeplki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwYWpyaXdydXNydmtya2VwbGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDQ0MzgsImV4cCI6MjA2OTg4MDQzOH0.hmXnAy-FlP_Z29oVyeEE5wmKI5CYw81_lpsf5w21tHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});